CC=g++
CFLAGS=-Wall -std=c++17
BINS=progPlantilla
all: clean programa

programa:
	$(CC) $(CFLAGS) -o progPlantilla progPlantilla.cpp

clean:
	@echo " [CLN] Removing binary files... chao!!"
	@rm -f $(BINS)
