# Compilador
CC = g++

# Opciones de compilación
CFLAGS = -std=c++17 -pthread -Wall

# Rutas a los archivos fuente
SRCDIR = Src
FUNCIONESDIR = $(SRCDIR)/ExternalProcesses

# Directorios de destino para los ejecutables
OUTPUT = $(SRCDIR)/Out

# Fuentes
SOURCES_FUNCIONES = $(wildcard $(FUNCIONESDIR)/*.cpp)
SOURCES_MAIN = $(SRCDIR)/main.cpp

# Nombres de archivos fuente sin extensión
EXECUTABLES_FUNCIONES = $(basename $(notdir $(SOURCES_FUNCIONES)))
EXECUTABLE_MAIN = main

# Nombres de ejecutables sin extensión con ruta de salida
EXECUTABLES_WITH_PATH_FUNCIONES = $(addprefix $(OUTPUT)/,$(EXECUTABLES_FUNCIONES))
EXECUTABLE_MAIN_WITH_PATH = $(OUTPUT)/$(EXECUTABLE_MAIN)

.PHONY: all clean run_% rebuild

all: $(EXECUTABLES_WITH_PATH_FUNCIONES) $(EXECUTABLE_MAIN_WITH_PATH)

# Regla para construir ejecutables en FUNCIONESDIR
$(EXECUTABLES_WITH_PATH_FUNCIONES): $(OUTPUT)/%: $(FUNCIONESDIR)/%.cpp
	$(CC) $(CFLAGS) $< -o $@ -lstdc++fs

# Regla para construir el ejecutable main
$(EXECUTABLE_MAIN_WITH_PATH): $(SOURCES_MAIN)
	$(CC) $(CFLAGS) $< -o $@ -lstdc++fs

# Regla para construir y ejecutar
run_%: $(OUTPUT)/%
	./$<

all: $(EXECUTABLES_WITH_PATH_FUNCIONES) $(EXECUTABLE_MAIN_WITH_PATH)

clean:
	rm -f $(EXECUTABLES_WITH_PATH_FUNCIONES) $(EXECUTABLE_MAIN_WITH_PATH)

rebuild: clean all
